# setup environment
dist: bionic
language: ruby
cache: bundler

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-yaml"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
    rvm: 2.5
  - os: linux
    rvm: 2.5
    env: ATOM_CHANNEL=beta

# execute tests
install: gem install --no-document travis
before_script: echo "y" | travis --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
