# setup environment
dist: jammy
language: ruby
cache: bundler

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-yaml'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'

os: linux
rvm: 2.7

# execute tests
install: gem install --no-document travis
before_script: echo 'y' | travis --version
script: 'curl -s https://raw.githubusercontent.com/mschuchard/vagrant-boxes-docker-images/master/atom-build-package.sh | sh'
