---
name: ci

on:
  push:
    branches: [master]
    paths:
    - '**.js'
  pull_request:
    branches: [master]
    paths:
    - '**.js'

env:
  CI: true
  PACKAGES: 'language-ruby'

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        channel: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.channel }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - name: install dependencies
      run: apm install && apm install ${PACKAGES} && apm clean
    - name: lint source and spec
      run: ./node_modules/.bin/eslint lib spec || true
    - name: install travis
      run: gem install --no-document travis
    - name: run tests
      run: atom --test spec
